url: https://www.hauntingtheatom.com
title: Haunting The Atom
tagline: Lo-fi synth sounds with horror/sci-fi videos
description: Lo-fi synth sounds and short films on a horror/sci-fi trip
locale: en_GB
google_analytics: G-YMFT576QWS
masthead: /assets/images/haunting-the-atom-masthead.png

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%e %B %Y"
  social_links:
    - { platform: facebook,  user_url: "https://www.facebook.com/hauntingtheatom" }
    - { platform: twitter,  user_url: "https://twitter.com/hauntingtheatom" }
    - { platform: instagram,  user_url: "https://www.instagram.com/haunting.the.atom/" }
    - { platform: youtube,  user_url: "https://www.youtube.com/@hauntingtheatom" }

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/haunting-the-atom-social.jpg
