title: Haunting The Atom
tagline: Lo-fi synth sounds on a horror and sci-fi trip
description: Lo-fi synth sounds, often with videos, on a horror and sci-fi trip. Novice. Dunno what I'm doing but I enjoy it.
locale: en_GB

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%e %B %Y"
  social_links:
    facebook: hauntingtheatom
    twitter: hauntingtheatom
    youtube_channel: UCdUo6OgsREERuIbCqLd9TOg
    youtube_channel_name: Haunting The Atom
    bandcamp: hauntingtheatom
