title: Haunting The Atom
tagline: Lo-fi synth sounds with horror/sci-fi videos
description: Lo-fi synth sounds and short films on a horror/sci-fi trip
locale: en_GB
google_analytics: G-YMFT576QWS
masthead: /assets/images/haunting-the-atom-masthead.png

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%e %B %Y"
  social_links:
    facebook: hauntingtheatom
    twitter: hauntingtheatom
    instagram: haunting.the.atom
    youtube_channel: UCdUo6OgsREERuIbCqLd9TOg
    youtube_channel_name: Haunting The Atom
    bandcamp: hauntingtheatom

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/haunting-the-atom-social.jpg
